version: '3.3'

services:

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'pruebascalcu'
      MYSQL_USER: 'oscar'
      MYSQL_PASSWORD: 'adminoscar'
      MYSQL_ROOT_PASSWORD: 'adminoscar'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-db-data:/var/lib/mysql
    networks:
      - app_net

  backend:
    image: '7771512001/back_so1_practica1_1s2023'
    container_name: 'backend'
    restart: always
    ports:
      - '5005:5005'
    depends_on:
      - db
    networks:
    - app_net
    volumes:
      - ./home/oscar/Desktop:/home
    # links:
    #   - db

  frontend:
    image: 7771512001/front_so1_practica1_1s2023
    container_name: front
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

networks:
  app_net:
    driver: bridge

volumes:
  mysql-db-data:

