-- Crear la secuencia
CREATE SEQUENCE seq_id
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 999999999999 
	MINVALUE 1
	NOCYCLE
	NOCACHE;

--CREAR EL TRIGGER
CREATE OR REPLACE TRIGGER tr_autoincrement_ubicaciones
	BEFORE INSERT ON ubicaciones
	FOR EACH ROW 
BEGIN 
	SELECT seq_id.NEXTVAL
	INTO :NEW.id
	FROM dual;
END;

--Crear las tablas
SELECT * FROM DB_Excel;
SELECT * FROM estado;
INSERT INTO estado(descripcion) values('1TETRgACICLINA');
DELETE FROM estado WHERE id = 5;
DELETE FROM TEMP_TABLA ;
DROP TABLE victimas;
UPDATE estado SET id = 1 WHERE id = 4;
ALTER SEQUENCE seq_id RESTART ;

--Creacion de TABLAS
--INSERCION DE DATOS (LUEGO DE CREAR TODAS LAS TABLAS)
--MOSTRAR DATOS

SELECT DISTINCT DB_EXCEL.NOMBRE_VICTIMA,DB_EXCEL.APELLIDO_VICTIMA,DB_EXCEL.DIRECCION_VICTIMA,
TO_DATE(DB_EXCEL.FECHA_PRIMERA_SOSPECHA,'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_CONFIRMACION,'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_MUERTE,'DD/MM/YYYY HH24:MI'),
ESTADO.ID
FROM DB_EXCEL 
INNER JOIN ESTADO
	ON DB_EXCEL.ESTADO_VICTIMA = estado.DESCRIPCION 
WHERE NOMBRE_VICTIMA IS NOT NULL AND APELLIDO_VICTIMA IS NOT NULL
AND DIRECCION_VICTIMA IS NOT NULL AND FECHA_PRIMERA_SOSPECHA IS NOT NULL 
AND FECHA_CONFIRMACION IS NOT NULL;


INSERT INTO reg_victima_hospital(idvictima,idhospital)
SELECT DISTINCT victimas.ID,hospitales.ID
FROM DB_EXCEL
	INNER JOIN HOSPITALES
	ON DB_EXCEL.NOMBRE_HOSPITAL = HOSPITALES.NOMBRE AND DB_EXCEL.DIRECCION_HOSPITAL = HOSPITALES.DIRECCION 
	INNER JOIN VICTIMAS
	ON DB_EXCEL.NOMBRE_VICTIMA = victimas.nombre AND DB_EXCEL.APELLIDO_VICTIMA =VICTIMAS.APELLIDO; 

INSERT INTO UBICACION_VICTIMA (FECHA_LLEGADA,FECHA_RETIRO,IDVICTIMA,IDUBICACION)
SELECT DISTINCT TO_DATE(DB_EXCEL.FECHA_LLEGADA,'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_RETIRO,'DD/MM/YYYY HH24:MI'),
VICTIMAS.ID,UBICACIONES.ID
FROM DB_EXCEL
INNER JOIN VICTIMAS
ON DB_EXCEL.NOMBRE_VICTIMA = VICTIMAS.NOMBRE AND DB_EXCEL.APELLIDO_VICTIMA =VICTIMAS.APELLIDO
INNER JOIN UBICACIONES
ON DB_EXCEL.UBICACION_VICTIMA = UBICACIONES.DIRECCION;

INSERT INTO TRATAMIENTO_VICTIMA (FECHA_INICIO,FECHA_FIN,EFECTIVIDAD_EN_VICTIMA,IDVICTIMA,IDTRATAMIENTO)
SELECT DISTINCT TO_DATE(DB_EXCEL.FECHA_INICIO_TRATAMIENTO,'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_FIN_TRATAMIENTO,'DD/MM/YYYY HH24:MI'),
DB_EXCEL.EFECTIVIDAD_EN_VICTIMA,
VICTIMAS.ID,TRATAMIENTOS.ID
FROM DB_EXCEL
INNER JOIN VICTIMAS
ON DB_EXCEL.NOMBRE_VICTIMA = VICTIMAS.NOMBRE AND DB_EXCEL.APELLIDO_VICTIMA =VICTIMAS.APELLIDO 
INNER JOIN TRATAMIENTOS
ON DB_EXCEL.TRATAMIENTO = TRATAMIENTOS.NOMBRE
;

INSERT INTO REGISTRO_ASOCIADO (FECHA_CONOCIO,IDASOCIADO,IDVICTIMA)
SELECT DISTINCT TO_DATE(DB_EXCEL.FECHA_CONOCIO,'DD/MM/YYYY HH24:MI'),
ASOCIADOS.ID ,VICTIMAS.ID 
FROM DB_EXCEL
INNER JOIN ASOCIADOS
ON DB_EXCEL.NOMBRE_ASOCIADO = ASOCIADOS.NOMBRE AND DB_EXCEL.APELLIDO_ASOCIADO = ASOCIADOS.APELLIDO 
INNER JOIN VICTIMAS
ON DB_EXCEL.NOMBRE_VICTIMA = VICTIMAS.NOMBRE AND DB_EXCEL.APELLIDO_VICTIMA  = VICTIMAS.APELLIDO ;

/*SELECT DISTINCT TO_DATE(DB_EXCEL.FECHA_INICIO_CONTACTO,'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_FIN_CONTACTO,'DD/MM/YYYY HH24:MI'),
TIPOS_CONTACTO.ID ,REGISTRO_CONTACTO.ID 
FROM DB_EXCEL
INNER JOIN TIPOS_CONTACTO
ON DB_EXCEL.CONTACTO_FISICO = TIPOS_CONTACTO.DESCRIPCION 
INNER JOIN REGISTRO_ASOCIADO
ON REGISTRO_ASOCIADO.

*
* TO_DATE(DB_EXCEL.FECHA_INICIO_CONTACTO, 'DD/MM/YYYY HH24:MI'),
TO_DATE(DB_EXCEL.FECHA_FIN_CONTACTO,'DD/MM/YYYY HH24:MI'),
*
**/
INSERT INTO REGISTRO_CONTACTO (fecha_inicio,FECHA_FIN,IDCONTACTO,IDREGISTRO)
SELECT DISTINCT TO_DATE(FECHA_INICIO_CONTACTO,'DD/MM/YYYY HH24:MI' ), 
TO_DATE(FECHA_FIN_CONTACTO,'DD/MM/YYYY HH24:MI' ),
TIPOS_CONTACTO.ID,
victimas.ID,
asociados.ID 
FROM DB_EXCEL
INNER JOIN VICTIMAS
ON VICTIMAS.NOMBRE = DB_EXCEL.NOMBRE_VICTIMA AND VICTIMAS.APELLIDO = DB_EXCEL.APELLIDO_VICTIMA 
INNER JOIN ASOCIADOS
ON ASOCIADOS.NOMBRE = DB_EXCEL.NOMBRE_ASOCIADO AND ASOCIADOS.APELLIDO = DB_EXCEL.APELLIDO_ASOCIADO 
INNER JOIN TIPOS_CONTACTO
ON TIPOS_CONTACTO.DESCRIPCION  = DB_EXCEL.CONTACTO_FISICO 
INNER JOIN REGISTRO_ASOCIADO
ON REGISTRO_ASOCIADO.IDVICTIMA = VICTIMAS.ID AND REGISTRO_ASOCIADO.IDASOCIADO = ASOCIADOS.ID ;

INSERT INTO REGISTRO_CONTACTO (fecha_inicio,FECHA_FIN,IDCONTACTO,IDREGISTRO)
SELECT DISTINCT TO_DATE(FECHA_INICIO_CONTACTO,'DD/MM/YYYY HH24:MI' ), 
TO_DATE(FECHA_FIN_CONTACTO,'DD/MM/YYYY HH24:MI' ),
TIPOS_CONTACTO.ID,
REGISTRO_ASOCIADO.ID
FROM DB_EXCEL
INNER JOIN VICTIMAS
ON VICTIMAS.NOMBRE = DB_EXCEL.NOMBRE_VICTIMA AND VICTIMAS.APELLIDO = DB_EXCEL.APELLIDO_VICTIMA 
INNER JOIN ASOCIADOS
ON ASOCIADOS.NOMBRE = DB_EXCEL.NOMBRE_ASOCIADO AND ASOCIADOS.APELLIDO = DB_EXCEL.APELLIDO_ASOCIADO 
INNER JOIN TIPOS_CONTACTO
ON TIPOS_CONTACTO.DESCRIPCION  = DB_EXCEL.CONTACTO_FISICO 
INNER JOIN REGISTRO_ASOCIADO
ON REGISTRO_ASOCIADO.IDVICTIMA = VICTIMAS.ID AND REGISTRO_ASOCIADO.IDASOCIADO = ASOCIADOS.ID;

SELECT * FROM estado;
SELECT * FROM TRATAMIENTOS t ;
SELECT * FROM UBICACIONES u  ;
SELECT * FROM VICTIMAS ;
SELECT * FROM hospitales;
SELECT * FROM REG_VICTIMA_HOSPITAL ;
SELECT * FROM TRATAMIENTO_VICTIMA ;
SELECT * FROM REGISTRO_ASOCIADO ;
SELECT * FROM DB_EXCEL e ;

DROP TABLE estado;
DROP TABLE victimas;
DROP TABLE hospitales;
DROP TABLE UBICACIONES ;

DROP TABLE DB_EXCEL ;


SELECT v.NOMBRE ,v.APELLIDO ,v.DIRECCION
FROM VICTIMAS v 
INNER JOIN REG_VICTIMA_HOSPITAL rvh ON
rvh.IDVICTIMA = v.ID 
INNER JOIN (SELECT IDVICTIMA ,count(IDASOCIADO) AS NUM_ALLEGADOS 
	FROM REGISTRO_ASOCIADO 
	GROUP BY IDVICTIMA) ra ON 
	ra.IDVICTIMA = v.ID 
INNER JOIN (SELECT IDVICTIMA, COUNT(IDTRATAMIENTO) AS NUM_TRATAMIENTOS
	FROM TRATAMIENTO_VICTIMA 
	GROUP BY IDVICTIMA) tv ON 
	tv.IDVICTIMA = v.ID
WHERE ra.NUM_ALLEGADOS < 2
AND tv.NUM_TRATAMIENTOS = 2
AND RVH.IDVICTIMA  = V.ID ;


SELECT V.NOMBRE, V.APELLIDO,V.DIRECCION
FROM VICTIMAS v 
INNER JOIN (SELECT IDVICTIMA,)


SELECT * FROM VICTIMAS v 
INNER JOIN (SELECT IDVICTIMA, COUNT(IDASOCIADO) AS NUM_ALLEGADOS 
	FROM REGISTRO_ASOCIADO ra2 
	GROUP BY IDVICTIMA ) ra3  ON 
	ra3.IDVICTIMA = v.ID
WHERE ra3.NUM_ALLEGADOS < 2;



SELECT
MAX(victimas.nombre) AS nombre_victima,
MAX(victimas.apellido) AS apellido_victima,
MAX(victimas.direccion) AS direccion_victima,
COUNT(*) AS total
FROM detalle_tratamientos
INNER JOIN victimas
ON detalle_tratamientos.victima_id = victimas.id
GROUP BY victimas.id
HAVING COUNT(*) = 2
ORDER BY nombre_victima;


SELECT idvictima, COUNT(idasociado) AS cantidad_asociados 
FROM registro_asociado 
GROUP BY idvictima;


SELECT v.nombre, v.apellido, v.direccion
FROM victimas v
JOIN reg_victima_hospital rvh ON v.id = rvh.idvictima
JOIN registro_asociado ra ON v.id = ra.idvictima
JOIN tratamiento_victima tv ON v.id = tv.idvictima
WHERE ra.idasociado IS NOT NULL
GROUP BY v.id, v.nombre, v.apellido, v.direccion
HAVING COUNT(DISTINCT ra.idasociado) < 3
   AND COUNT(DISTINCT rvh.idhospital) > 0
   AND COUNT(DISTINCT tv.idtratamiento) = 2;
   
  
  
 -- Consulta 10
  
SELECT h.nombre AS Nombre_hospital, tc.nombre AS Nombre_contacto,
	COUNT(*)*100/(SELECT COUNT(*) FROM REG_VICTIMA_HOSPITAL rvh
  		INNER JOIN VICTIMAS v ON rvh.IDVICTIMA = v.ID
  			WHERE rvh.IDHOSPITAL = h.id) AS Porcentaje_Victimas
FROM HOSPITALES h 
INNER JOIN REG_VICTIMA_HOSPITAL rvh2 ON h.ID  = rvh2.IDHOSPITAL 
INNER JOIN VICTIMAS v2 ON rvh2.IDVICTIMA = v2.ID 
INNER JOIN (
	SELECT h.
	FROM REGISTRO_CONTACTO rc 
)



SELECT NOMBRE ,DESCRIPCION ,PORCENTAJE_VICTIMAS
FROM (SELECT H.NOMBRE ,TC.DESCRIPCION ,COUNT(*)*100.0/(
		SELECT DISTINCT COUNT(*)
		FROM REGISTRO_ASOCIADO ra 
		INNER JOIN VICTIMAS v ON RA.IDVICTIMA = V.ID 
		INNER JOIN REG_VICTIMA_HOSPITAL rvh ON RVH.IDVICTIMA = V.ID 
		INNER JOIN HOSPITALES ho ON RVH.IDHOSPITAL = ho.ID 
		WHERE H.ID = ho.ID 
	) AS PORCENTAJE_VICTIMAS,
	ROW_NUMBER () OVER (PARTITION BY H.NOMBRE ORDER BY COUNT(*) DESC) AS N
	FROM VICTIMAS v2 
	INNER JOIN REGISTRO_ASOCIADO ra2 ON RA2.IDVICTIMA =V2.ID 
	INNER JOIN REGISTRO_CONTACTO rc ON RC.IDREGISTRO = RA2.ID 
	INNER JOIN TIPOS_CONTACTO tc ON TC.ID = RC.IDCONTACTO 
	INNER JOIN REG_VICTIMA_HOSPITAL rvh2 ON RVH2.IDVICTIMA =V2.ID 
	INNER JOIN HOSPITALES h ON H.ID = RVH2.IDHOSPITAL 
	GROUP BY H.NOMBRE ,TC.DESCRIPCION ,H.ID 
)
WHERE N = 1
ORDER BY PORCENTAJE_VICTIMAS DESC;





-- Consulta 10 Prueba
SELECT H.ID, CONTACTO_FISICO,PORCENTAJE_VICTIMAS
FROM (
    SELECT h.NOMBRE_HOSPITAL, contact.CONTACTO_FISICO, COUNT(*) * 100.0 / (
        SELECT DISTINCT COUNT(*)
        FROM REGISTRO_ASOCIADO ra
        INNER JOIN VICTIMAS v ON V.ID = ra.IDVICTIMA 
        INNER JOIN REG_VICTIMA_HOSPITAL rvh ON RVH.IDVICTIMA = V.ID 
        INNER JOIN HOSPITALES h ON tb_h.idtb_hospital = trh.tb_hospital_idtb_hospital
        WHERE tb_h.idtb_hospital = h.idtb_hospital
) AS PORCENTAJE_VICTIMAS,
ROW_NUMBER() OVER (PARTITION BY h.NOMBRE_HOSPITAL ORDER BY COUNT(*) DESC) AS n
FROM
tb_victima tbv
INNER JOIN tb_registro_asociado tbra ON tbra.tb_victimas_idtb_victimas = tbv.idtb_victima
INNER JOIN tb_contacto contact ON contact.idtb_contacto = tbra.tb_contacto_idtb_contacto
INNER JOIN tb_registro_hospital tprh ON tprh.tb_victimas_idtb_victimas = tbv.idtb_victima
INNER JOIN tb_hospital h ON h.idtb_hospital = tprh.tb_hospital_idtb_hospital
GROUP BY
h.nombre_hospital,
contact.CONTACTO_FISICO,
h.idtb_hospital
)
WHERE n= 1
ORDER BY  V_PORCETNAJE DESC;

--Consulta 7
SELECT v.NOMBRE ,v.APELLIDO ,v.DIRECCION
FROM VICTIMAS v 
INNER JOIN REG_VICTIMA_HOSPITAL rvh ON
rvh.IDVICTIMA = v.ID 
INNER JOIN (SELECT IDVICTIMA ,count(DISTINCT IDASOCIADO) AS NUM_ALLEGADOS 
	FROM REGISTRO_ASOCIADO 
	GROUP BY IDVICTIMA) ra ON 
	ra.IDVICTIMA = v.ID 
INNER JOIN (SELECT IDVICTIMA, COUNT(DISTINCT IDTRATAMIENTO) AS NUM_TRATAMIENTOS
	FROM TRATAMIENTO_VICTIMA 
	GROUP BY IDVICTIMA) tv ON 
	tv.IDVICTIMA = v.ID
WHERE ra.NUM_ALLEGADOS  < 3
AND tv.NUM_TRATAMIENTOS = 2
AND RVH.IDVICTIMA  = V.ID ;
UNION 
SELECT v.nombre, v.apellido,v.direccion
FROM VICTIMAS v 
INNER JOIN reg

