version: '3.3'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=pruebascalcu
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=adminoscar
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql